
package com.akash.spring.crm.test.webservices.soap.services;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.akash.spring.crm.test.webservices.soap.model.actions.GetAllIncompleteActionsRequest;
import com.akash.spring.crm.test.webservices.soap.model.actions.GetAllIncompleteActionsResponse;
import com.akash.spring.crm.test.webservices.soap.model.actions.RecordActionRequest;
import com.akash.spring.crm.test.webservices.soap.model.calls.CreateCallRequest;
import com.akash.spring.crm.test.webservices.soap.model.calls.RemoveCallRequest;
import com.akash.spring.crm.test.webservices.soap.model.calls.UpdateCallRequest;
import com.akash.spring.crm.test.webservices.soap.model.customers.AddCustomerRequest;
import com.akash.spring.crm.test.webservices.soap.model.customers.DeleteCustomerRequest;
import com.akash.spring.crm.test.webservices.soap.model.customers.GetCustomerByCompanyNameRequest;
import com.akash.spring.crm.test.webservices.soap.model.customers.GetCustomerByCompanyNameResponse;
import com.akash.spring.crm.test.webservices.soap.model.customers.GetCustomerByIdRequest;
import com.akash.spring.crm.test.webservices.soap.model.customers.GetCustomerByIdResponse;
import com.akash.spring.crm.test.webservices.soap.model.customers.GetFullCustomerDetailsRequest;
import com.akash.spring.crm.test.webservices.soap.model.customers.GetFullCustomerDetailsResponse;
import com.akash.spring.crm.test.webservices.soap.model.customers.UpdateCustomerRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRMService", targetNamespace = "http://www.akash.com/crm/crmservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.akash.spring.crm.test.webservices.soap.model.actions.ObjectFactory.class,
    com.akash.spring.crm.test.webservices.soap.model.calls.ObjectFactory.class,
    com.akash.spring.crm.test.webservices.soap.model.customers.ObjectFactory.class
})
public interface CRMService {


    /**
     * 
     * @param getFullCustomerDetailsRequest
     * @return
     *     returns com.akash.crm.customers.GetFullCustomerDetailsResponse
     */
    @WebMethod
    @WebResult(name = "getFullCustomerDetailsResponse", targetNamespace = "http://www.akash.com/crm/customers", partName = "getFullCustomerDetailsResponse")
    public GetFullCustomerDetailsResponse getFullCustomerDetails(
        @WebParam(name = "getFullCustomerDetailsRequest", targetNamespace = "http://www.akash.com/crm/customers", partName = "getFullCustomerDetailsRequest")
        GetFullCustomerDetailsRequest getFullCustomerDetailsRequest);

    /**
     * 
     * @param deleteCustomerRequest
     */
    @WebMethod
    @Oneway
    public void deleteCustomer(
        @WebParam(name = "deleteCustomerRequest", targetNamespace = "http://www.akash.com/crm/customers", partName = "deleteCustomerRequest")
        DeleteCustomerRequest deleteCustomerRequest);

    /**
     * 
     * @param recordActionRequest
     */
    @WebMethod
    @Oneway
    public void recordAction(
        @WebParam(name = "recordActionRequest", targetNamespace = "http://www.akash.com/crm/actions", partName = "recordActionRequest")
        RecordActionRequest recordActionRequest);

    /**
     * 
     * @param getCustomerByCompanyNameRequest
     * @return
     *     returns com.akash.crm.customers.GetCustomerByCompanyNameResponse
     */
    @WebMethod
    @WebResult(name = "getCustomerByCompanyNameResponse", targetNamespace = "http://www.akash.com/crm/customers", partName = "getCustomerByCompanyNameResponse")
    public GetCustomerByCompanyNameResponse getCustomerByCompanyName(
        @WebParam(name = "getCustomerByCompanyNameRequest", targetNamespace = "http://www.akash.com/crm/customers", partName = "getCustomerByCompanyNameRequest")
        GetCustomerByCompanyNameRequest getCustomerByCompanyNameRequest);

    /**
     * 
     * @param addCustomerRequest
     */
    @WebMethod
    @Oneway
    public void addCustomer(
        @WebParam(name = "addCustomerRequest", targetNamespace = "http://www.akash.com/crm/customers", partName = "addCustomerRequest")
        AddCustomerRequest addCustomerRequest);

    /**
     * 
     * @param getCustomerByIdRequest
     * @return
     *     returns com.akash.crm.customers.GetCustomerByIdResponse
     */
    @WebMethod
    @WebResult(name = "getCustomerByIdResponse", targetNamespace = "http://www.akash.com/crm/customers", partName = "getCustomerByIdResponse")
    public GetCustomerByIdResponse getCustomerById(
        @WebParam(name = "getCustomerByIdRequest", targetNamespace = "http://www.akash.com/crm/customers", partName = "getCustomerByIdRequest")
        GetCustomerByIdRequest getCustomerByIdRequest);

    /**
     * 
     * @param getAllIncompleteActionsRequest
     * @return
     *     returns com.akash.crm.actions.GetAllIncompleteActionsResponse
     */
    @WebMethod
    @WebResult(name = "getAllIncompleteActionsResponse", targetNamespace = "http://www.akash.com/crm/actions", partName = "getAllIncompleteActionsResponse")
    public GetAllIncompleteActionsResponse getAllIncompleteActions(
        @WebParam(name = "getAllIncompleteActionsRequest", targetNamespace = "http://www.akash.com/crm/actions", partName = "getAllIncompleteActionsRequest")
        GetAllIncompleteActionsRequest getAllIncompleteActionsRequest);

    /**
     * 
     * @param updateCallRequest
     */
    @WebMethod
    @Oneway
    public void updateCall(
        @WebParam(name = "updateCallRequest", targetNamespace = "http://www.akash.com/crm/calls", partName = "updateCallRequest")
        UpdateCallRequest updateCallRequest);

    /**
     * 
     * @param updateCustomerRequest
     */
    @WebMethod
    @Oneway
    public void updateCustomer(
        @WebParam(name = "updateCustomerRequest", targetNamespace = "http://www.akash.com/crm/customers", partName = "updateCustomerRequest")
        UpdateCustomerRequest updateCustomerRequest);

    /**
     * 
     * @param removeCallRequest
     */
    @WebMethod
    @Oneway
    public void removeCall(
        @WebParam(name = "removeCallRequest", targetNamespace = "http://www.akash.com/crm/calls", partName = "removeCallRequest")
        RemoveCallRequest removeCallRequest);

    /**
     * 
     * @param createCallRequest
     */
    @WebMethod
    @Oneway
    public void createCall(
        @WebParam(name = "createCallRequest", targetNamespace = "http://www.akash.com/crm/calls", partName = "createCallRequest")
        CreateCallRequest createCallRequest);

}
