//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.27 at 04:10:25 PM EDT 
//


package com.akash.spring.crm.webservices.soap.xml.actions;

import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import com.akash.spring.crm.model.Action;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="action" type="{http://www.akash.com/crm/actions}action" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "action"
})
@XmlRootElement(name = "getAllIncompleteActionsResponse")
public class GetAllIncompleteActionsResponse {

    protected List<ActionXML> action;
    
    public GetAllIncompleteActionsResponse() {}


    public GetAllIncompleteActionsResponse(List<Action> actions) {
    	action = new ArrayList<ActionXML>();
    	for (Action act : actions) {
    		ActionXML actionXML = new ActionXML();
    		actionXML.setOwner(act.getOwner());
    		actionXML.setDetails(act.getDetails());
    		GregorianCalendar gcal = new GregorianCalendar();
    		gcal.setTime(act.getRequiredBy().getTime());
    		XMLGregorianCalendar xgcal = null;
			try {
				xgcal = DatatypeFactory.newInstance().newXMLGregorianCalendar(gcal);
			} catch (DatatypeConfigurationException e) {
				e.printStackTrace();
			}
    		actionXML.setRequiredBy(xgcal);
    		action.add(actionXML);
    		actionXML = null;
    	}
    }
    /**
     * Gets the value of the action property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the action property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionXML }
     * 
     * 
     */
    public List<ActionXML> getAction() {
        if (action == null) {
            action = new ArrayList<ActionXML>();
        }
        return this.action;
    }

}
