//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 02:57:39 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.akash.com/crm/actions")
package com.akash.spring.crm.webservices.soap.xml.actions;
