//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.27 at 11:15:26 AM EDT 
//


package com.akash.spring.crm.webservices.soap.xml.customers;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.GregorianCalendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import com.akash.spring.crm.model.Call;
import com.akash.spring.crm.model.Customer;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customer" type="{http://www.akash.com/crm/customers}customer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customer"
})
@XmlRootElement(name = "getCustomerByIdResponse")
public class GetCustomerByIdResponse {

    @XmlElement(required = true)
    protected CustomerXML customer;

    public GetCustomerByIdResponse() {
		// TODO Auto-generated constructor stub
	}

    public GetCustomerByIdResponse(Customer customer) {
    	this.customer = new CustomerXML();
    	this.customer.setCompany(customer.getCompany());
    	this.customer.setCustomerNotes(customer.getCustomerNotes());
    	this.customer.setEmail(customer.getEmail());
    	this.customer.setId(customer.getId());
    	for (Call call : customer.getCalls()) {
    		com.akash.spring.crm.webservices.soap.xml.calls.CallXML callXML = new com.akash.spring.crm.webservices.soap.xml.calls.CallXML();
    		callXML.setCallNotes(call.getCallNotes());
    		LocalDateTime callTime = call.getCallTime();
    		GregorianCalendar gcal = GregorianCalendar.from(callTime.atZone(ZoneId.systemDefault()));
    		XMLGregorianCalendar xgcal = null;
			try {
				xgcal = DatatypeFactory.newInstance().newXMLGregorianCalendar(gcal);
			} catch (DatatypeConfigurationException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    		callXML.setCallTime(xgcal);
    		this.customer.getCalls().add(callXML);
    		callXML = null;
    	}
    	this.customer.setTelephone(customer.getTelephone());
    }
    
    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerXML }
     *     
     */
    public CustomerXML getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerXML }
     *     
     */
    public void setCustomer(CustomerXML value) {
        this.customer = value;
    }

}
